"""
DXF writer: assembles projected views and AI dimensioning into a 2D drawing.

Uses ezdxf to create a DXF file with:
- Orthographic views placed in standard positions
- Hidden lines as dashed
- Dimensions from the AI engine
- A basic title block
"""

import ezdxf
from ezdxf.enums import TextEntityAlignment
from typing import List, dict
import os


# Drawing layout constants (in mm, at the drawing's internal scale)
SCALE = 1.0
GAP_BETWEEN_VIEWS = 50  # mm spacing between views
TITLE_BLOCK_W = 180
TITLE_BLOCK_H = 40


def _add_segments_to_msp(msp, segments, offset_x, offset_y, scale=1.0):
    """Add line segments from projection to the DXF modelspace."""
    for seg in segments:
        pts = seg["points"]
        is_hidden = seg["type"] == "hidden"

        if is_hidden:
            linetype = "DASHED"
            layer = "HIDDEN"
        else:
            linetype = "CONTINUOUS"
            layer = "VISIBLE"

        if len(pts) < 2:
            continue

        # Group consecutive point pairs into lines
        for i in range(0, len(pts) - 1, 2):
            x1, y1 = pts[i][0] * scale + offset_x, pts[i][1] * scale + offset_y
            x2, y2 = pts[i + 1][0] * scale + offset_x, pts[i + 1][1] * scale + offset_y
            msp.add_line(
                (x1, y1), (x2, y2),
                dxfattribs={"layer": layer, "linetype": linetype}
            )


def _add_title_block(msp, origin_x, origin_y, part_name, metadata):
    """Add a simple title block in the bottom-right corner."""
    x, y = origin_x, origin_y

    # Border
    msp.add_lwpolyline(
        [(x, y), (x + TITLE_BLOCK_W, y), (x + TITLE_BLOCK_W, y + TITLE_BLOCK_H),
         (x, y + TITLE_BLOCK_H), (x, y)],
        close=True, dxfattribs={"layer": "TITLE_BLOCK"}
    )

    # Internal divider line
    msp.add_line(
        (x, y + TITLE_BLOCK_H / 2),
        (x + TITLE_BLOCK_W, y + TITLE_BLOCK_H / 2),
        dxfattribs={"layer": "TITLE_BLOCK"}
    )

    # Text
    bb = metadata.bounding_box["size"]
    text_lines = [
        f"PART: {part_name}",
        f"SIZE: {bb[0]:.1f} x {bb[1]:.1f} x {bb[2]:.1f} mm",
        f"GENERATED BY: CAD Drawing AI",
    ]

    for i, line in enumerate(text_lines):
        msp.add_text(
            line,
            height=3,
            dxfattribs={"layer": "TITLE_BLOCK_TEXT"}
        ).set_placement((x + 5, y + TITLE_BLOCK_H - 5 - i * 5))


def _add_dimension(msp, dim, offset_x, offset_y):
    """Add a single dimension to the drawing based on AI output."""
    dim_type = dim.get("type", "linear")
    view_offset_x = offset_x + dim.get("view_offset_x", 0)
    view_offset_y = offset_y + dim.get("view_offset_y", 0)

    if dim_type == "linear":
        p1 = (dim["from"][0] + view_offset_x, dim["from"][1] + view_offset_y)
        p2 = (dim["to"][0] + view_offset_x, dim["to"][1] + view_offset_y)
        angle = dim.get("angle", 0)  # 0 = horizontal, 90 = vertical

        if abs(p2[0] - p1[0]) > abs(p2[1] - p1[1]):
            # Horizontal dimension
            msp.add_linear_dim(
                base=(p1[0], p1[1] + dim.get("offset", 15)),
                p1=p1, p2=p2,
                angle=0,
                dxfattribs={"layer": "DIMENSIONS"}
            )
        else:
            # Vertical dimension
            msp.add_linear_dim(
                base=(p1[0] + dim.get("offset", 15), p1[1]),
                p1=p1, p2=p2,
                angle=90,
                dxfattribs={"layer": "DIMENSIONS"}
            )

    elif dim_type == "diameter":
        center = (dim["center"][0] + view_offset_x, dim["center"][1] + view_offset_y)
        radius = dim["radius"]
        msp.add_circle(
            center, radius,
            dxfattribs={"layer": "DIMENSIONS"}
        )
        msp.add_text(
            f"Ø{dim.get('label', radius * 2)}",
            height=3,
            dxfattribs={"layer": "DIMENSIONS"}
        ).set_placement((center[0] + radius + 3, center[1]))

    elif dim_type == "radius":
        center = (dim["center"][0] + view_offset_x, dim["center"][1] + view_offset_y)
        radius = dim["radius"]
        msp.add_text(
            f"R{radius}",
            height=3,
            dxfattribs={"layer": "DIMENSIONS"}
        ).set_placement((center[0] + radius + 3, center[1]))


def write_dxf(
    views: dict,
    metadata,
    dimensions: list,
    output_path: str,
    part_name: str = None,
) -> str:
    """
    Assemble all views and dimensions into a DXF drawing.

    Args:
        views: dict from view_projector.project_all_views()
        metadata: PartMetadata from step_parser
        dimensions: list of dimension dicts from ai_dim
        output_path: where to save the .dxf file
        part_name: override part name for title block

    Returns: path to the saved DXF file
    """
    if part_name is None:
        part_name = metadata.filename

    doc = ezdxf.new(dxfversion="R2010", setup=True)

    # Set up linetypes
    if "DASHED" not in doc.linetypes:
        doc.linetypes.add("DASHED", pattern="A,5,-3", description="Dashed __ __ __")

    # Create layers
    doc.layers.add("VISIBLE", color=7)       # white/black
    doc.layers.add("HIDDEN", color=8)        # gray
    doc.layers.add("DIMENSIONS", color=3)    # green
    doc.layers.add("TITLE_BLOCK", color=7)
    doc.layers.add("TITLE_BLOCK_TEXT", color=7)

    msp = doc.modelspace()

    # Layout positions for each view
    # Front view: bottom-left
    # Top view: above front
    # Right view: right of front
    front_w = views.get("front", {}).get("width", 100)
    front_h = views.get("front", {}).get("height", 100)
    top_h = views.get("top", {}).get("height", 100)
    right_w = views.get("right", {}).get("width", 100)

    base_x = 50
    base_y = 50

    layout = {
        "front": (base_x, base_y),
        "top":   (base_x, base_y + front_h + GAP_BETWEEN_VIEWS),
        "right": (base_x + front_w + GAP_BETWEEN_VIEWS, base_y),
    }

    # Add each view
    for view_name, (ox, oy) in layout.items():
        view_data = views.get(view_name, {})
        segments = view_data.get("segments", [])
        if segments:
            _add_segments_to_msp(msp, segments, ox, oy)

    # Add dimensions
    for dim in dimensions:
        view_name = dim.get("view", "front")
        ox, oy = layout.get(view_name, (base_x, base_y))
        try:
            _add_dimension(msp, dim, ox, oy)
        except Exception as e:
            print(f"  [warn] failed to add dimension: {e}")

    # Title block (bottom-right of the drawing)
    tb_x = base_x + front_w + right_w + GAP_BETWEEN_VIEWS * 2
    tb_y = base_y
    _add_title_block(msp, tb_x, tb_y, part_name, metadata)

    # Save
    doc.saveas(output_path)
    print(f"  DXF saved: {output_path}")
    return output_path
